// Code generated by "stringer -type=MessageType"; DO NOT EDIT.

package wsrpc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CodeMessageRequest-0]
	_ = x[CodeMessageReply-1]
	_ = x[CodeRawProto-2]
	_ = x[CodeClientHelloRequest-3]
	_ = x[CodeClientHelloReply-4]
	_ = x[CodeRequestComingRequest-5]
	_ = x[CodeRequestComingReply-6]
	_ = x[CodeRequestGrpcServiceRequest-7]
	_ = x[CodeRequestGrpcServiceReply-8]
	_ = x[CodeRequestNsbServiceRequest-9]
	_ = x[CodeRequestNsbServiceReply-10]
	_ = x[CodeSessionListRequest-11]
	_ = x[CodeSessionListReply-12]
	_ = x[CodeTransactionListRequest-13]
	_ = x[CodeTransactionListReply-14]
	_ = x[CodeUserRegisterRequest-15]
	_ = x[CodeUserRegisterReply-16]
	_ = x[CodeSessionFinishedRequest-17]
	_ = x[CodeSessionFinishedReply-18]
	_ = x[CodeSessionRequireTransactRequest-19]
	_ = x[CodeSessionRequireTransactReply-20]
	_ = x[CodeAttestationReceiveRequest-21]
	_ = x[CodeAttestationReceiveReply-22]
	_ = x[CodeAttestationSendingRequest-23]
	_ = x[CodeAttestationSendingReply-24]
	_ = x[CodeCloseSessionRequest-25]
	_ = x[CodeCloseSessionReply-26]
}

const _MessageType_name = "CodeMessageRequestCodeMessageReplyCodeRawProtoCodeClientHelloRequestCodeClientHelloReplyCodeRequestComingRequestCodeRequestComingReplyCodeRequestGrpcServiceRequestCodeRequestGrpcServiceReplyCodeRequestNsbServiceRequestCodeRequestNsbServiceReplyCodeSessionListRequestCodeSessionListReplyCodeTransactionListRequestCodeTransactionListReplyCodeUserRegisterRequestCodeUserRegisterReplyCodeSessionFinishedRequestCodeSessionFinishedReplyCodeSessionRequireTransactRequestCodeSessionRequireTransactReplyCodeAttestationReceiveRequestCodeAttestationReceiveReplyCodeAttestationSendingRequestCodeAttestationSendingReplyCodeCloseSessionRequestCodeCloseSessionReply"

var _MessageType_index = [...]uint16{0, 18, 34, 46, 68, 88, 112, 134, 163, 190, 218, 244, 266, 286, 312, 336, 359, 380, 406, 430, 463, 494, 523, 550, 579, 606, 629, 650}

func (i MessageType) String() string {
	if i >= MessageType(len(_MessageType_index)-1) {
		return "MessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MessageType_name[_MessageType_index[i]:_MessageType_index[i+1]]
}
