//go:generate package-attach-to-path -generate_register_map
package service

import (
	"fmt"
	"github.com/Myriad-Dreamin/go-ves/central-ves/control"
	"github.com/Myriad-Dreamin/minimum-lib/module"
	"path"
)

type SubController interface {
	GetControllers() []interface{}
}

type subController struct {
	controllers []interface{}
}

func (s subController) GetControllers() []interface{} {
	return s.controllers
}

func JustProvide(controllers ...interface{}) SubController {
	return subController{controllers: controllers}
}

// @DocName Minimum-go-ves/central-ves
// @Description this is documentation of the go-ves/central-ves backend powered by minimum, autogenerated.
type Provider struct {
	chainInfoService ChainInfoService
	module.BaseModuler

	objectService ObjectService
	userService   UserService
	authService   AuthService

	subControllers []SubController
}

func NewProvider(namespace string) *Provider {
	return &Provider{
		BaseModuler: module.BaseModuler{
			Namespace: namespace,
		},
		subControllers: []SubController{JustProvide(control.AdditionControllerDescs...)},
	}
}

func (s *Provider) Register(name string, service interface{}) {
	if err := s.Provide(path.Join(s.Namespace, name), service); err != nil {
		panic(fmt.Errorf("unknown/registered service %T, err %v", service, err))
	}

	switch ss := service.(type) {
	case ChainInfoService:
		s.chainInfoService = ss
		s.subControllers = append(s.subControllers, JustProvide(&ss))
		return
	case UserService:
		s.userService = ss
		s.subControllers = append(s.subControllers, JustProvide(&ss))
		return
	case AuthService:
		s.authService = ss
		s.subControllers = append(s.subControllers, JustProvide(&ss))
		return
	case ObjectService:
		s.objectService = ss
		s.subControllers = append(s.subControllers, JustProvide(&ss))
		return
	default:
		//if ss, ok := service.(SubController); ok {
		//	s.subControllers = append(s.subControllers, ss)
		//}
		panic(fmt.Errorf("unknown service %T", service))
	}
}

// for documents
func (s *Provider) GetControllers() []interface{} {
	var controllers []interface{}
	for i := range s.subControllers {
		controllers = append(controllers, s.subControllers[i].GetControllers()...)
	}
	return controllers
}

func (s *Provider) GetProvider() interface{} {
	return s
}
